# Generated by Django 4.0.2 on 2022-02-16 07:39

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('estado_codigo', models.BigAutoField(primary_key=True, serialize=False)),
                ('estado_nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('persona_codigo', models.BigIntegerField(primary_key=True, serialize=False)),
                ('persona_nombre', models.CharField(max_length=50)),
                ('persona_documento', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Publicidad',
            fields=[
                ('publicidad_codigo', models.BigAutoField(primary_key=True, serialize=False)),
                ('publicidad_tipo', models.CharField(max_length=50)),
                ('publicidad_ruta', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('sede_codigo', models.BigAutoField(primary_key=True, serialize=False)),
                ('sede_nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('servicio_codigo', models.BigAutoField(primary_key=True, serialize=False)),
                ('servicio_nombre', models.CharField(max_length=50, unique=True)),
                ('servicio_prefijo', models.CharField(max_length=2, unique=True)),
                ('servicio_prioridad', models.BigIntegerField()),
                ('servicio_consecutivoactual', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Caja',
            fields=[
                ('caja_codigo', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='UserApp.servicio')),
                ('caja_nombre', models.CharField(max_length=50, unique=True)),
                ('servicio_codigo', models.BigIntegerField()),
                ('sede_codigo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='UserApp.sede')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('sede_codigo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='UserApp.sede')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ProgramaPublicidad',
            fields=[
                ('ppublicidad_codigo', models.BigAutoField(primary_key=True, serialize=False)),
                ('ppublicidad_tiempo', models.BigIntegerField()),
                ('ppublicidad_orden', models.BigIntegerField()),
                ('publicidad_codigo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='UserApp.publicidad')),
            ],
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('turno_codigo', models.BigAutoField(primary_key=True, serialize=False)),
                ('turno_fecha', models.DateField()),
                ('truno_hora', models.TimeField()),
                ('turno_fechaejecucion', models.DateField(blank=True, null=True)),
                ('turno_horaejecucion', models.TimeField(blank=True, null=True)),
                ('turno_consecutivo', models.BigIntegerField()),
                ('estado_codigo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='UserApp.estado')),
                ('persona_codigo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='UserApp.persona')),
                ('servicio_codigo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='UserApp.servicio')),
                ('caja_codigo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='UserApp.caja')),
            ],
        ),
    ]
