# Generated by Django 4.0.2 on 2022-02-06 02:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('estado_codigo', models.BigAutoField(primary_key=True, serialize=False)),
                ('estado_nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('persona_codigo', models.BigIntegerField(primary_key=True, serialize=False)),
                ('persona_nombre', models.CharField(max_length=50)),
                ('persona_documento', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Publicidad',
            fields=[
                ('publicidad_codigo', models.BigAutoField(primary_key=True, serialize=False)),
                ('publicidad_tipo', models.CharField(max_length=50)),
                ('publicidad_ruta', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('rol_codigo', models.BigAutoField(primary_key=True, serialize=False)),
                ('rol_nombre', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('sede_codigo', models.BigAutoField(primary_key=True, serialize=False)),
                ('sede_nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('servicio_codigo', models.BigAutoField(primary_key=True, serialize=False)),
                ('servicio_nombre', models.CharField(max_length=50, unique=True)),
                ('servicio_prefijo', models.CharField(max_length=2, unique=True)),
                ('servicio_prioridad', models.BigIntegerField()),
                ('servicio_consecutivoactual', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Caja',
            fields=[
                ('caja_codigo', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='UserApp.servicio')),
                ('caja_nombre', models.CharField(max_length=50, unique=True)),
                ('servicio_codigo', models.BigIntegerField()),
                ('sede_codigo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='UserApp.sede')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('usuario_codigo', models.BigAutoField(primary_key=True, serialize=False)),
                ('usuario_login', models.CharField(blank=True, max_length=50, null=True)),
                ('usuario_clave', models.CharField(blank=True, max_length=50, null=True)),
                ('rol_codigo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='UserApp.rol')),
                ('sede_codigo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='UserApp.sede')),
            ],
        ),
        migrations.CreateModel(
            name='ProgramaPublicidad',
            fields=[
                ('ppublicidad_codigo', models.BigAutoField(primary_key=True, serialize=False)),
                ('ppublicidad_tiempo', models.BigIntegerField()),
                ('ppublicidad_orden', models.BigIntegerField()),
                ('publicidad_codigo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='UserApp.publicidad')),
            ],
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('turno_codigo', models.BigAutoField(primary_key=True, serialize=False)),
                ('turno_fecha', models.DateField()),
                ('truno_hora', models.TimeField()),
                ('turno_fechaejecucion', models.DateField(blank=True, null=True)),
                ('turno_horaejecucion', models.TimeField(blank=True, null=True)),
                ('turno_consecutivo', models.BigIntegerField()),
                ('estado_codigo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='UserApp.estado')),
                ('persona_codigo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='UserApp.persona')),
                ('servicio_codigo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='UserApp.servicio')),
                ('caja_codigo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='UserApp.caja')),
            ],
        ),
    ]
