# Generated by Django 4.0.2 on 2022-02-27 02:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0003_rename_truno_hora_turno_turno_hora_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turno',
            name='estado_codigo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='UserApp.estado'),
        ),
    ]
