# Generated by Django 4.0.2 on 2022-02-27 02:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0004_alter_turno_estado_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caja',
            name='sede_codigo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='UserApp.sede'),
        ),
        migrations.AlterField(
            model_name='caja',
            name='servicio_codigo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='UserApp.servicio'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='sede_codigo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='UserApp.sede'),
        ),
    ]
