# Generated by Django 4.0.2 on 2022-03-15 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0005_alter_caja_sede_codigo_alter_caja_servicio_codigo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='persona_codigo',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='publicidad',
            name='publicidad_tipo',
            field=models.CharField(choices=[('IMAGEN', 'IMAGEN'), ('VIDEO', 'VIDEO'), ('AUDIO', 'AUDIO')], max_length=50),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='servicio_consecutivoactual',
            field=models.BigIntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='servicio_prioridad',
            field=models.FloatField(blank=True, default='0', null=True),
        ),
        migrations.AlterField(
            model_name='turno',
            name='turno_fecha',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='turno',
            name='turno_hora',
            field=models.TimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status'),
        ),
    ]
