# Generated by Django 4.0.2 on 2022-03-18 04:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0006_alter_persona_persona_codigo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='caja',
            name='usuario_codigo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, unique=True),
        ),
        migrations.CreateModel(
            name='VwTurno',
            fields=[
                ('turno_codigo', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='Codigo de turno')),
                ('persona_nombre', models.CharField(max_length=50, verbose_name='Nombre del usuario de turno')),
                ('persona_documento', models.CharField(max_length=50, verbose_name='Documento de la persona')),
                ('servicio_nombre', models.CharField(max_length=50, verbose_name='Nombre del Servicio')),
                ('consecutivo', models.CharField(max_length=50, verbose_name='Consecutivo')),
                ('turno_fecha', models.DateField(blank=True, null=True, verbose_name='Fecha del turno')),
                ('turno_hora', models.TimeField(blank=True, null=True, verbose_name='Hora del Turno')),
                ('prioridadservicio', models.FloatField(blank=True, null=True, verbose_name='Prioridad del servicio')),
                ('estado_codigo', models.BigIntegerField(verbose_name='Estado del Servicio')),
                ('estado_nombre', models.CharField(max_length=50, verbose_name='Estado')),
                ('prioridad', models.FloatField(blank=True, null=True, verbose_name='Prioridad del servicio')),
                ('tiempominutos', models.FloatField(blank=True, null=True, verbose_name='Prioridad del servicio')),
                ('caja_codigo', models.BigIntegerField(verbose_name='Codigo Id de la Caja')),
                ('caja_nombre', models.CharField(max_length=50, verbose_name='Nombre de la Caja')),
                ('servicio_codigo_id', models.ForeignKey(db_column='servicio_codigo_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='UserApp.servicio')),
            ],
            options={
                'db_table': 'vw_turnos',
            },
        ),
    ]
