# Generated by Django 4.0.2 on 2022-03-18 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0007_caja_usuario_codigo_vwturno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caja',
            name='usuario_codigo',
        ),
        migrations.AddField(
            model_name='caja',
            name='username',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
